version: '3.5'

networks:
  proxy:
    external: true

services:
  ghost:
    container_name: sussike
    image: ghost:alpine
    restart: unless-stopped
    environment:
      - database_client=mysql
      - database_connection_host=ghost-db
      - database_connection_user=sussike
      - database_connection_password=mustikakissell
      - database_connection_database=sussike
      - NODE_ENV=production
      - url=https://sussike.ee
    volumes:
      - /home/wauhost/src/apps/sussike-ee/data:/var/lib/ghost/content
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.sussike-secured.rule=Host(`sussike.ee`,`www.sussike.ee`)"
      - "traefik.http.routers.sussike-secured.entrypoints=websecure"
    networks:
      - proxy
    depends_on:
      - ghost-db
      
  ghost-db:
    image: mysql:8.0
    restart: unless-stopped
    container_name: sussike-db
    cap_add:
      - SYS_NICE
    environment:
      - MYSQL_ROOT_PASSWORD=mustikakissell
      - MYSQL_DATABASE=sussike
      - MYSQL_USER=sussike
      - MYSQL_PASSWORD=mustikakissell
      - MYSQL_ROOT_HOST=172.*.*.*
    volumes:
      - /home/wauhost/src/apps/sussike-ee/db:/var/lib/mysql